local neogen = require("neogen")
neogen.setup({ snippet_engine = "luasnip" })

local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<leader>nf", function()
    neogen.generate({ type = 'func' })
end, opts)
vim.keymap.set("n", "<leader>nc", function()
    neogen.generate({ type = 'class' })
end, opts)
vim.keymap.set("n", "<leader>nt", function()
    neogen.generate({ type = 'type' })
end, opts)
vim.keymap.set("n", "<leader>nh", function()
    neogen.generate({ type = 'file' })
end, opts)
